# Generated by Django 3.0 on 2019-12-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iteration",
            options={"verbose_name": "Iteration", "verbose_name_plural": "Iterations"},
        ),
        migrations.AlterModelOptions(
            name="useraccount",
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
            },
        ),
    ]
