# Generated by Django 3.0.7 on 2020-09-24 14:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_auto_20200924_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer", name="name", field=models.CharField(max_length=50),
        ),
    ]
