# Generated by Django 3.0.7 on 2020-09-24 14:05
import datetime

import django.db.models.deletion

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_auto_20200924_1400"),
    ]

    operations = [
        migrations.RemoveField(model_name="customeraccount", name="user",),
        migrations.AddField(
            model_name="customeraccount",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="src.Customer",
            ),
            preserve_default=False,
        ),
    ]
