# Generated by Django 3.0.7 on 2020-10-27 05:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0009_auto_20200926_0232"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("APPROVED", "APPROVED")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
